# Generated by Django 4.1.7 on 2023-03-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lightning_remove_post_comments_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
