# Generated by Django 4.1.7 on 2023-03-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
    ]
